version: '3.7'

services:
  web:
    build:
      context: .
    command: /bin/sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./bank:/bank
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  bot:
    build:
      context: .
    volumes:
      - ./bot:/bank/bot
    command: sh -c "uvicorn bot.main:app --host 0.0.0.0 --port 2727 --reload"
    ports:
      - "2727:2727"
    env_file:
      - ./.env
    depends_on:
      - web
      - redis
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=walletdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kappa
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "./config/redis.conf:/redis.conf"
    command: ["redis-server", "/redis.conf"]


volumes:
  postgres_data:
