version: '3.7'

services:
  bot:
    build:
      context: .
    volumes:
      - ./bot:/bank/bot
    command: [
      "sh",
      "-c",
      "pip install debugpy && python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn bot.main:app --reload --host 0.0.0.0 --port 2727",
    ]
    ports:
      - "2727:2727"
      - "5678:5678"
    env_file:
      - ./.env

volumes:
  postgres_data:
