version: '3.7'

services:
  web:
    build:
      context: .
    command: /bin/sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./bank:/bank
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  bot:
    build:
      context: .
    volumes:
      - ./bot:/bank/bot
    command: sh -c "uvicorn bot.main:app --host 0.0.0.0 --port 2727 --reload"
    ports:
      - "2727:2727"
    env_file:
      - ./.env

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=walletdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kappa
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    logging:
      driver: none

volumes:
  postgres_data:
