# Generated by Django 4.0.3 on 2022-03-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallets',
            name='wallet_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
