# Generated by Django 4.0.3 on 2022-03-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_wallets_wallet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallets',
            name='cash',
            field=models.IntegerField(default=10000),
        ),
    ]
