# Generated by Django 4.0.3 on 2022-03-28 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_wallets_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='from_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_wallet', to='api.wallets'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='to_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_wallet', to='api.wallets'),
        ),
    ]
