# Generated by Django 4.0.3 on 2022-03-29 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_transactions_from_wallet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallets',
            old_name='cash',
            new_name='balance',
        ),
        migrations.AddField(
            model_name='transactions',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
