# Generated by Django 4.0.3 on 2022-03-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_cash_wallets_balance_transactions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='comment',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
