# Generated by Django 4.0.3 on 2022-04-01 13:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_transactions_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='from_wallet',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='to_wallet',
        ),
        migrations.AddField(
            model_name='transactions',
            name='wallet',
            field=models.ForeignKey(default=uuid.UUID('ce1fdc93-ec92-422e-b4ca-707234a5a7b3'), on_delete=django.db.models.deletion.CASCADE, related_name='trans_wallet', to='api.wallets'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='whence',
            field=models.CharField(default='asd', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.users'),
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=128, null=True)),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_wallet', to='api.wallets')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_wallet', to='api.wallets')),
            ],
        ),
    ]
