# Generated by Django 4.0.3 on 2022-04-01 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_transactions_from_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='payment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactions',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans_wallet', to='api.wallets'),
        ),
    ]
