# Generated by Django 4.0.3 on 2022-04-05 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_wallet_name_wallets_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whence', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment', models.PositiveIntegerField()),
                ('comment', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='transfers',
            name='from_wallet',
        ),
        migrations.RemoveField(
            model_name='transfers',
            name='to_wallet',
        ),
        migrations.RenameModel(
            old_name='Wallets',
            new_name='Wallet',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
        migrations.DeleteModel(
            name='Transfers',
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_wallet', to='api.wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_wallet', to='api.wallet'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('to_wallet__isnull', True), ('whence__isnull', False)), models.Q(('to_wallet__isnull', False), ('whence__isnull', True)), _connector='OR'), name='api_transaction_to_wallet_or_not'),
        ),
    ]
