# Generated by Django 4.0.3 on 2022-04-22 12:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_transaction_rename_users_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_wallet', to='api.wallet', verbose_name='Initializer Wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_wallet', to='api.wallet', verbose_name='Recipient Wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='whence',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Where/From where the money should be sent/received'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(max_length=128, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Wallet ID'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Wallet name'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.user', verbose_name='User'),
        ),
    ]
