# Generated by Django 4.0.3 on 2022-05-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Wallet name'),
        ),
    ]
