# Generated by Django 4.0.4 on 2022-05-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_wallet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vk_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='VK ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
